services:
  mysql-main:
    image: mysql:8.0
    container_name: exam-backend-mysql-main
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exam-backend-db
      MYSQL_USER: exam-backend-user
      MYSQL_PASSWORD: exam-backend-password
    ports:
      - "3306:3306"
    volumes:
      - mysql-main-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      
  mysql-log:
    image: mysql:8.0
    container_name: exam-backend-mysql-log
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exam-backend-log
      MYSQL_USER: exam-backend-user
      MYSQL_PASSWORD: exam-backend-password
    ports:
      - "3307:3306"
    volumes:
      - mysql-log-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      
  redis:
    image: redis:alpine
    container_name: exam-backend-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-main-data:
  mysql-log-data:
  redis-data:
