services:
  mysql:
    image: mysql:8.0
    container_name: exam-backend-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exam-backend-db
      MYSQL_USER: exam-backend-user
      MYSQL_PASSWORD: exam-backend-password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  mysql-data:
